# config.py
# CONFIGURAÇÃO PRINCIPAL DE ACESSO À BASE DE DADOS (MYSQL - LAGOSTIM)

MYSQL_DATABASE_USER = 'geral'
MYSQL_DATABASE_PASSWORD = 'teclaDo+4'
MYSQL_DATABASE_DB = 'dbsimplegui_rodrigo'
MYSQL_DATABASE_HOST = '62.28.39.135'
