# config.py
# CONFIGURAÇÃO PRINCIPAL DE ACESSO À BASE DE DADOS (MYSQL - LAGOSTIM)

MYSQL_DATABASE_USER = 'geral'
MYSQL_DATABASE_PASSWORD = 'SECRET'
MYSQL_DATABASE_DB = 'NAME'
MYSQL_DATABASE_HOST = 'IP'
